name: CD Workflow

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploying image ${{ github.event.inputs.image_tag }}"